name: Bug Report
description: Found a bug? Use this form to open an issue so we can get it fixed.
title: "[Bug]: <insert title here>"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report for SeedSigner! 
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search [existing issues](https://github.com/SeedSigner/seedsigner/issues) to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Suggested Fix
      description: If you have a suggestion on how to fix this bug please let us know. Alternatively if you can code a fix you can open up a [pull request](https://github.com/SeedSigner/seedsigner/pulls) with the updated code to fix the issue.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Images? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
