blank_issues_enabled: true
contact_links:
  - name: I have a question or need support
    url: https://github.com/EverydayBitcoiner/seedsigner/discussions
    about: Please ask and answer questions here.
