name: Documentation
description: See something in the docs that needs to be fixed/updated/added? Use this form to open an issue so we can get it fixed.
title: "[Documentation]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this documentation report for SeedSigner! 
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search [existing issues](https://github.com/SeedSigner/seedsigner/issues) to see if an issue already exists for fixing, updating, or adding what you have found.
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    attributes:
      label: Current Documentation (if applicable)
      description: A concise description of what the current documentation shows or describes.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Proposed Documentation
      description: A concise description of what you want the documentation should look like.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Images? Anything that will give us more context about the documentation issue!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
