name: General R&D Proposal
description: Have a proposal for R&D work to improve Seedsigner? Use this form to open an issue so we can take a look.
title: "[R&D]: "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this R&D report for SeedSigner! 
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search [existing issues](https://github.com/SeedSigner/seedsigner/issues) to see if an issue already exists for this R&D idea.
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    attributes:
      label: Proposed R&D
      description: A concise description of what R&D you are proposing.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Proposed R&D Value
      description: A concise description of why you think this R&D work would be valuable.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Images? Anything that will give us more context about the proposed R&D work!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
